### ISSUE TITLE
Change GAMS template file

### ISSUE THREAD

**Issue by ptrkrnstnr** [vwmaus/model-reproducibility#14]
exchange variables to user variables

**Comment by ptrkrnstnr** [comment]
@vwmaus please take a look at the latest GAMS template file. In the last lines the variable GAMS_PATH is used with $GAMS_PATH. Is that right or must it be ${GAMS_PATH}, ... or is the syntax ${variable} only used for ENV variables? thank you!

**Comment by vwmaus** [comment]
@ptrkrnstnr both should work, but braces are compulsory in the wget command within Dockerfile.
