### ISSUE TITLE
edit Dockerfile-model

### ISSUE THREAD

**Issue by ptrkrnstnr** [vwmaus/model-reproducibility#34]
exchange variables

#Model_version# - must be all git tags OR branches from a repository (not only from master-branch but also from features, etc) zb: master, featureX, v1.0, etc...

**Comment by ptrkrnstnr** [comment]
@vwmaus done, you can see now the branches + tags in the dropdown menu. Do we have to differentiate between branch or tag later on? I think the url is different if you want to pull from a specific tag or a specific branch...
![grafik](https://user-images.githubusercontent.com/32832927/33531061-78ff3efe-d888-11e7-9da5-fdebf7bfd180.png)

**Comment by vwmaus** [comment]
the link is the same. I clone the full repo into the image and checkout to the selected tag or branch.
